CREATE TABLE tblCustomer
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[FirstName] NVARCHAR(100) NOT NULL,
	[LastName] NVARCHAR(100) NOT NULL,
	[Email] NVARCHAR(255) NOT NULL,
	[PhoneNumber] NVARCHAR(20) NULL,
	[CreatedAt] DATETIMEOFFSET NOT NULL,
	[ModifiedAt] DATETIMEOFFSET NULL,
	[ArchivedAt] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),

	CONSTRAINT PK_Customer PRIMARY KEY (Id),

	INDEX IX_Customer_Email NONCLUSTERED (Email),
	INDEX IX_Customer_ArchivedAt NONCLUSTERED (ArchivedAt)
)
