CREATE TABLE tblDataSource
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[DataSourceType] NVARCHAR(50) NOT NULL,
	[LogoUrl] NVARCHAR(500) NULL,
	[IsActive] BIT NOT NULL,
	[CreatedAt] DATETIMEOFFSET NOT NULL,
	[ModifiedAt] DATETIMEOFFSET NULL,
	[ArchivedAt] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),

	CONSTRAINT PK_DataSource PRIMARY KEY (Id),

	INDEX IX_DataSource_Name NONCLUSTERED (Name),
	INDEX IX_DataSource_ArchivedAt NONCLUSTERED (ArchivedAt)
)
