CREATE TABLE tblPaymentMethod
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[PaymentMethodType] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(500) NULL,
	[CreatedAt] DATETIMEOFFSET NOT NULL,
	[ModifiedAt] DATETIMEOFFSET NULL,
	[ArchivedAt] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),

	CONSTRAINT PK_PaymentMethod PRIMARY KEY (Id),

	INDEX IX_PaymentMethod_Name NONCLUSTERED (Name),
	INDEX IX_PaymentMethod_ArchivedAt NONCLUSTERED (ArchivedAt)
)
